config/routes.rb
Rails.application.routes.draw do


  devise_for :authors
  root to: 'blog/_posts#index'

  # /author/posts
  namespace :authors do
  	# Defining all the possible routes that matches controller actions in 
  	# the post controllers
  	resources :posts  	
  end

  # rootpath/posts
  scope module: 'blog' do 
  	# => == points the about resource to...
  	get 'about' => 'pages#about', as: :about
  	get 'contact' => 'pages#contact', as: :contact
  	get 'posts' => 'post#index', as: :posts  	
  	get 'posts/:id' => 'posts#show', as: :post
  end 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord
	extend FriendlyId
  	friendly_id :title, use: :slugged

    # Delete the optional after an Author is created
    belongs_to :author, optional: true

  	# Take the itens we want and give it in a descending order
  	scope :most_recent, -> { order(id: :desc)}

  	# part of the friendly_id code base
  	def should_generate_new_friendly_id?
  		# part of the rails code base
  		title_changed?
  	end

  	def display_published_date
  		#string from time
      "Published #{created_at.strftime('%-b %-d, %Y')}"
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # Only used by the application controller, the others are overwritten by the author of the blog	 
  layout 'author'


end

app/controllers/author/posts_controller.rb
#name Spacing moduling
module Author
	class PostsController < AuthorController
	  before_action :set_post, only: [:show, :edit, :update, :destroy]

	  # GET /posts
	  # GET /posts.json
	  def index
	    @posts = Post.most_recent
	  end

	  # GET /posts/1
	  # GET /posts/1.json
	  def show
	  end

	  # GET /posts/new
	  def new
	    @post = Post.new
	  end

	  # GET /posts/1/edit
	  def edit
	  end

	  # POST /posts
	  # POST /posts.json
	  def create
	    @post = Post.new(post_params)

	    respond_to do |format|
	      if @post.save
	        format.html { redirect_to author_post_path(@post), notice: 'Post was successfully created.' }
	        format.json { render :show, status: :created, location: @post }
	      else
	        format.html { render :new }
	        format.json { render json: @post.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  # PATCH/PUT /posts/1
	  # PATCH/PUT /posts/1.json
	  def update
	    respond_to do |format|
	      if @post.update(post_params)
	        format.html { redirect_to author_post_path(@post), notice: 'Post was successfully updated.' }
	        format.json { render :show, status: :ok, location: @post }
	      else
	        format.html { render :edit }
	        format.json { render json: @post.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  # DELETE /posts/1
	  # DELETE /posts/1.json
	  def destroy
	    @post.destroy
	    respond_to do |format|
	      format.html { redirect_to author_posts_url, notice: 'Post was successfully destroyed.' }
	      format.json { head :no_content }
	    end
	  end

	  private
	    # Use callbacks to share common setup or constraints between actions.
	    def set_post
	      # Looks for a post in the database, based on the id.  
	      # friendly gives a nive string instead of numbers    
	      @post = Post.friendly.find(params[:id])
	    end

	    # Never trust parameters from the scary internet, only allow the white list through.
	    def post_params
	      params.require(:post).permit(:title, :body, :description, :banner_image_url)
	    end
	end
end

app/controllers/author_controller.rb
# Controller for the Author part of the application, since it is split for different users
# and to not have a big application Controller for the whole website
class AuthorController < ApplicationController
  before_action :authenticate_author! 
end

app/controllers/authors/posts_controller.rb
#name Spacing moduling
module Authors
	class PostsController < AuthorController
	  before_action :set_post, only: [:show, :edit, :update, :destroy]

	  # GET /posts
	  # GET /posts.json
	  def index
	  	# If you want to show only the posts that an Author has created
	  	# @posts = current_author.posts.most_recent
	  	# Do that for all the actions
	    @posts = Post.most_recent
	  end

	  # GET /posts/1
	  # GET /posts/1.json
	  def show
	  end

	  # GET /posts/new
	  def new
	    @post = Post.new
	  end

	  # GET /posts/1/edit
	  def edit
	  end

	  # POST /posts
	  # POST /posts.json
	  def create
	    @post = Post.new(post_params)

	    respond_to do |format|
	      if @post.save
	        format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully created.' }
	        format.json { render :show, status: :created, location: @post }
	      else
	        format.html { render :new }
	        format.json { render json: @post.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  # PATCH/PUT /posts/1
	  # PATCH/PUT /posts/1.json
	  def update
	    respond_to do |format|
	      if @post.update(post_params)
	        format.html { redirect_to authors_post_path(@post), notice: 'Post was successfully updated.' }
	        format.json { render :show, status: :ok, location: @post }
	      else
	        format.html { render :edit }
	        format.json { render json: @post.errors, status: :unprocessable_entity }
	      end
	    end
	  end

	  # DELETE /posts/1
	  # DELETE /posts/1.json
	  def destroy
	    @post.destroy
	    respond_to do |format|
	      format.html { redirect_to authors_posts_url, notice: 'Post was successfully destroyed.' }
	      format.json { head :no_content }
	    end
	  end

	  private
	    # Use callbacks to share common setup or constraints between actions.
	    def set_post
	      # Looks for a post in the database, based on the id.  
	      # friendly gives a nive string instead of numbers    
	      @post = Post.friendly.find(params[:id])
	    end

	    # Never trust parameters from the scary internet, only allow the white list through.
	    def post_params
	      params.require(:post).permit(:title, :body, :description, :banner_image_url)
	    end
	end
end

app/controllers/blog/pages_controller.rb
# 
module Blog
	class PagesController < BlogController
		
		def about
		end

		def contact
		end

	end
end	

app/controllers/blog/posts_controller.rb
#name Spacing moduling
module Blog
	class PostsController < BlogController
	  before_action :set_post, only: [:show, :edit, :update, :destroy]

	  # GET /posts
	  # GET /posts.json
	  def index
	    @posts = Post.most_recent
	  end

	  # GET /posts/1
	  # GET /posts/1.json
	  def show
	  end
	  
	end
	
	
end

app/controllers/blog_controller.rb
# Controller for the Blog part of the application, since it is split for different users
# and to not have a big application Controller for the whole website
class BlogController < ApplicationController
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/author/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :post_description %>
  </div>

  <div class="field">
    <%= form.label :banner_image_url %>
    <%= form.text_area :banner_image_url%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/author/posts/edit.html.erb
<!-- Provide the page title -->
<% provide(:author, "Edit #{@post.title}") %>
<!-- put the word active where we yield blog_active -->
<% provide(:author, 'active') %>

<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/author/posts/index.html.erb
<!-- Provide the page title -->
<% provide(:page_title, 'All Posts') %>
<!-- put the word active where we yield blog_active -->
<% provide(:author, 'active') %>

<div class="row">
	<div>
	<%= link_to 'New Post', new_author_post_path, class: 'btn btn-primary btn-lg' %>	
	</div>
	<br>
	<table class="table table-striped">
		<tr>
			<th colspan="4">Title</th>			
		</tr>
		<%= render @posts %>	
	</table>
  
</div>

app/views/author/posts/show.html.erb
<!-- Provide the page title -->
<% provide(:page_title, @post.title) %>
<!-- put the word active where we yield blog_active -->
<% provide(:author, 'active') %>

<div>
	<%= link_to 'Edit', edit_author_post_path(@post), class: 'btn btn-sm btn-warning' %>
</div>


<div>
	<%= link_to 'Delete', author_post_path(@post), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-danger'  %>
</div>

<div class="row">
	<div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 - text-xs-center">
		<h1><%= @post.title %></h1>
		<p><%= @post.display_published_date %></p>
		<%= @post.body %>
	</div>
</div>

app/views/authors/posts/_form.html.erb
<%= form_for(post, url: url) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :post_description %>
  </div>

  <div class="field">
    <%= form.label :banner_image_url %>
    <%= form.text_area :banner_image_url%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/posts/_post.html.erb
<tr>
	<td><%= link_to post.title, authors_post_path(post) %></td>
	<td><%= link_to 'Edit', edit_authors_post_path(post), class: 'btn btn-sm btn-warning' %></td>
	<td><%= link_to 'Delete', authors_post_path(post), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-danger'  %></td>
</tr>

app/views/authors/posts/edit.html.erb
<!-- Provide the page title -->
<% provide(:author, "Edit #{@post.title}") %>
<!-- put the word active where we yield blog_active -->
<% provide(:author, 'active') %>

<h1>Editing Post</h1>

<%= render 'form', post: @post, url: authors_post_url(@post) %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', authors_posts_path %>

app/views/authors/posts/index.html.erb
<!-- Provide the page title -->
<% provide(:page_title, 'All Posts') %>
<!-- put the word active where we yield blog_active -->
<% provide(:author, 'active') %>

<div class="row">
	<div>
	<%= link_to 'New Post', new_authors_post_path, class: 'btn btn-primary btn-lg' %>	
	</div>
	<br>
	<table class="table table-striped">
		<tr>
			<th colspan="4">Title</th>			
		</tr>
		<%= render @posts %>	
	</table>
  
</div>

app/views/authors/posts/new.html.erb
<!-- Provide the page title -->
<% provide(:page_title, 'New Post') %>
<!-- put the word active where we yield blog_active -->
<% provide(:author, 'active') %>

<h1>New Post</h1>

<%= render 'form', post: @post, url: authors_posts_url %>

<%= link_to 'Back', posts_path %>

app/views/authors/posts/show.html.erb
<!-- Provide the page title -->
<% provide(:page_title, @post.title) %>
<!-- put the word active where we yield blog_active -->
<% provide(:author, 'active') %>

<div>
	<%= link_to 'Edit', edit_authors_post_path(@post), class: 'btn btn-sm btn-warning' %>
</div>


<div>
	<%= link_to 'Delete', authors_post_path(@post), method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-sm btn-danger'  %>
</div>

<div class="row">
	<div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 - text-xs-center">
		<h1><%= @post.title %></h1>
		<p><%= @post.display_published_date %></p>
		<%= @post.body %>
	</div>
</div>

app/views/blog/pages/about.html.erb
<% provide(:about_active, 'active') %>
<h1>About page</h1>

app/views/blog/pages/contact.html.erb
<% provide(:contact_active, 'active') %>
<h1>Contact Page</h1>

app/views/blog/posts/_post.html.erb
<!-- 
Partial that is read from the index of the posts 
post can be called without the @, since it inherits from the loop from index.html.erb	
-->
<div class='col-sm-6 col-lg-4'>
	<div class="card">
		<div class="card-topper" style='background-image: url(<%= post.banner_image_url %>);'>
		</div>
		<div class="card-block">
			<h4 class="card-title">
				<%= link_to post.title, post %>
			</h4>
			<p class="published-date">
				<%= post.display_published_date %>
			</p>
			<p class="card-text">
				<%= truncate(post.description, lenght:130) %>
			</p>
			<%= link_to 'Read', post, class: 'btn btn-read' %>
		</div>
	</div>
</div>

app/views/blog/posts/index.html.erb
<!-- Provide the page title -->
<% provide(:page_title, 'All Posts') %>
<!-- put the word active where we yield blog_active -->
<% provide(:blog_active, 'active') %>

<div class="row">
  <%= render @posts %>
</div>

app/views/blog/posts/show.html.erb
<!-- Provide the page title -->
<% provide(:page_title, @post.title) %>
<!-- put the word active where we yield blog_active -->
<% provide(:blog_active, 'active') %>

<div class="row">
	<div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2 - text-xs-center">
		<h1><%= @post.title %></h1>
		<p><%= @post.display_published_date %></p>
		<%= @post.body %>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<div class="collapse" id="exCollapsingNavbar">
  <div class="collapse-bg p-a-1">
    <div class='card'>
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
        </li>
        <% if author_signed_in? %>
          <li class="list-group-item">
            <%= link_to 'My Posts', authors_posts_path, class: "nav-link #{yield(:author)}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<nav class="navbar navbar-light bg-faded">
  <div class='container'>
    <a class='navbar-brand' href='/'>
      Ewerton <span class='light'>blog</span>
    </a>
    <button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
      &#9776;
    </button>
    <ul class="nav navbar-nav pull-sm-right hidden-xs-down">
      <li class="nav-item">
        <%= link_to 'Blog', root_path, class: "nav-link #{yield(:blog_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'About', about_path, class: "nav-link #{yield(:about_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Contact', contact_path, class: "nav-link #{yield(:contact_active)}" %>
      </li>
        <% if author_signed_in? %>
          <li class="nav-item">
            <%= link_to 'My Posts', authors_posts_path, class: "nav-link #{yield(:author)}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/author.html.erb
<!-- All the Author layouts are here since the application controller is split -->
<!DOCTYPE html>
<html>
  <head>
    <!-- Pass the title of each blog entry to the page -->
    <title><%= yield(:page_title) %> | Ewerton Ruiz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Render looks inside the views folder, and then follows the path -->
    <%= render 'layouts/navbar' %>
    <!-- Ensure flash messages for devise -->
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <!-- erb code passes the name of the controller and the action that it is on --> 
    <div class="container <%= controller_name %> <%= action_name %>">

      <%= yield %>  
    </div>
    
  </body>
</html>

app/views/layouts/blog.html.erb
<!-- All the blog layouts are here since the application controller is split -->
<!DOCTYPE html>
<html>
  <head>
    <!-- Pass the title of each blog entry to the page -->
    <title><%= yield(:page_title) %> | Ewerton Ruiz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- Render looks inside the views folder, and then follows the path -->
    <%= render 'layouts/navbar' %>
    <!-- erb code passes the name of the controller and the action that it is on --> 
    <div class="container <%= controller_name %> <%= action_name %>">

      <%= yield %>  
    </div>
    
  </body>
</html>